
-- Create the plans table
create table plans (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  currency text default '$',
  interval text default 'month',
  description text,
  cta text default 'Get Started',
  features text[] default '{}',
  is_popular boolean default false,
  is_dark boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table plans enable row level security;

-- Allow public read access
create policy "Public plans are viewable by everyone"
  on plans for select
  to anon
  using ( true );

-- Insert pricing plans
insert into plans (name, price, description, cta, features, is_popular, is_dark)
values
  (
    'Starter Plan',
    0,
    'Perfect for small teams getting started with task management.',
    'Get Started Free',
    ARRAY['Up to 5 team members', '3 projects maximum', 'Basic task management', 'Kanban board view', 'Email support', 'Mobile app access', '1GB storage'],
    false,
    false
  ),
  (
    'Professional Plan',
    12,
    'Everything growing teams need to scale productivity.',
    'Start 14-Day Free Trial',
    ARRAY['Unlimited team members', 'Unlimited projects', 'Advanced analytics dashboard', 'All project views', 'Priority email support', 'Custom workflows', 'Time tracking'],
    true,
    true
  ),
  (
    'Enterprise Plan',
    24,
    'Advanced features for large organizations and complex workflows.',
    'Contact Sales',
    ARRAY['Everything in Professional', 'Advanced security & compliance', 'Single Sign-On (SSO)', 'Custom branding', 'Dedicated customer success manager', 'Advanced API access', 'Custom integrations'],
    false,
    false
  );
