-- Create the table
create table testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  content text not null,
  avatar_url text,
  rating numeric default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table testimonials enable row level security;

-- Create a policy to allow anyone to read
create policy "Public testimonials are viewable by everyone"
  on testimonials for select
  to anon
  using ( true );

-- Insert sample data
insert into testimonials (name, role, content, avatar_url, rating)
values
  (
    'Sarah Larson',
    'Project Manager',
    'Planora has completely simplified how we manage projects across different departments. Before, we were constantly switching between spreadsheets, chat apps, and email just to keep track of tasks. Now, everything is organized in one dashboard that''s clear and easy to navigate.',
    'https://picsum.photos/seed/sarah/300/300',
    5
  ),
  (
    'Michael Chen',
    'Lead Developer',
    'The integration features are outstanding. Being able to see GitHub issues alongside our design tasks has improved our sprint velocity by 40%.',
    'https://picsum.photos/seed/michael/300/300',
    5
  ),
  (
    'Jessica Wu',
    'Product Designer',
    'I love the visual simplicity. It doesn''t feel like "work" to use Planora. The interface is beautiful and intuitive.',
    'https://picsum.photos/seed/jessica/300/300',
    4.5
  );
